revert privCA changes

diff --git a/installers/PrivacyCAServiceLinuxInstaller/src/files/pcactl b/installers/PrivacyCAServiceLinuxInstaller/src/files/pcactl
--- a/installers/PrivacyCAServiceLinuxInstaller/src/files/pcactl
+++ b/installers/PrivacyCAServiceLinuxInstaller/src/files/pcactl
@@ -22,7 +22,7 @@ glassfish_parent_dir=/usr/share
 #java_required_version=1.6.0_29
 #APPLICATION_YUM_PACKAGES="make gcc openssl libssl-dev"
 #APPLICATION_APT_PACKAGES="dpkg-dev make gcc openssl libssl-dev"
-glassfish_application_name=HisPrivacyCAWebServices2
+webservice_application_name=HisPrivacyCAWebServices2
 
 
 # FUNCTION LIBRARY, VERSION INFORMATION, and LOCAL CONFIGURATION
@@ -32,8 +32,9 @@ shell_include_files "${package_env_filename}" "${package_install_filename}"
 if [ -f /root/mtwilson.env ]; then  . /root/mtwilson.env; fi
 
 configure_privacyca_url() {
-  # PrivacyCaUrl = https://privacyca.server.com:8181/HisPrivacyCAWebServices2
+
   local privacyca_server privacyca_url
+
   if [ -n "$PRIVACYCA_SERVER" ]; then
     privacyca_server="$PRIVACYCA_SERVER"
   elif [ -n "$MTWILSON_SERVER" ]; then
@@ -41,7 +42,7 @@ configure_privacyca_url() {
   else
     prompt_with_default privacyca_server "Privacy CA Server:" 127.0.0.1
   fi
-  privacyca_url="https://${privacyca_server}:8181/HisPrivacyCAWebServices2"
+  privacyca_url="https://${privacyca_server}:$DEFAULT_API_PORT/HisPrivacyCAWebServices2"
   update_property_in_file PrivacyCaUrl "${intel_conf_dir}/privacyca-client.properties" "${privacyca_url}"
   # Now prompt for the client files download username and password
   #local privacyca_download_username PRIVACYCA_DOWNLOAD_PASSWORD
@@ -67,25 +68,47 @@ setup_print_summary() {
       echo "Glassfish: not found"
     fi
   fi
+  if using_tomcat; then
+    if [ -n "$TOMCAT_HOME" ]; then
+      TOMCAT_VERSION=`tomcat_version`
+      echo "Tomcat: $TOMCAT_VERSION"
+    else
+      echo "Tomcat: not found"
+    fi
+  fi
 }
 
 setup_interactive_install() {
   configure_privacyca_url
-  create_privacyca_keys
-  protect_privacyca_files
   if [ -n "$GLASSFISH_HOME" ]; then
     glassfish_running
     if [ -z "$GLASSFISH_RUNNING" ]; then
       glassfish_start_report
-    fi    
-    if [ -n "$MTWILSON_SETUP_NODEPLOY" ]; then
-      webservice_start_report "${glassfish_application_name}"
-    else
-      webservice_uninstall "${glassfish_application_name}"
-      webservice_install "${glassfish_application_name}" "${package_dir}"/HisPrivacyCAWebServices2.war
-      webservice_running_report "${glassfish_application_name}"
     fi
+  elif [ -n "$TOMCAT_HOME" ]; then
+    tomcat_running
+    if [ -z "$TOMCAT_RUNNING" ]; then
+      tomcat_start_report
+    fi
+  fi    
+
+  if [ -n "$MTWILSON_SETUP_NODEPLOY" ]; then
+    webservice_start_report "${webservice_application_name}"
+  else
+    webservice_uninstall "${webservice_application_name}"
+    webservice_install "${webservice_application_name}" "${package_dir}"/HisPrivacyCAWebServices2.war
+    #stall until deploy is done
+    local FINISH=0
+    while [ $FINISH -le 0 ]; do
+      if [ -f /etc/intel/cloudsecurity/PrivacyCA.p12 ]; then
+        FINISH=1
+      fi
+    done
+
+    webservice_running_report "${webservice_application_name}"
   fi
+  protect_privacyca_files
+
 }
 
 
@@ -93,46 +116,23 @@ setup() {
 #  mysql_clear; java_clear; glassfish_clear;
   mtwilson setup-env > "${package_env_filename}"
   . "${package_env_filename}"
-  if [[ -z "$JAVA_HOME" || -z "$GLASSFISH_HOME"  ]]; then
-      echo_warning "Missing one or more required packages"
-      setup_print_summary
-      exit 1
-  fi
+#  if [[ -z "$JAVA_HOME" || -z "$GLASSFISH_HOME"  ]]; then
+#      echo_warning "Missing one or more required packages"
+#      setup_print_summary
+#      exit 1
+#  fi
   setup_interactive_install
-}
-
-# This function temporarily replaces /dev/random with /dev/urandom and 
-# watches for the specified file... when the file exists then /dev/random
-# is restored.
-replace_random_until_exists() {
-  markerfile=$1
-  mv /dev/random /dev/random.old
-  ln -s /dev/urandom /dev/random
-  while [ ! -f "$markerfile" ]; do sleep 1; done
-  rm /dev/random
-  mv /dev/random.old /dev/random
-  if [ ! -e /dev/random ]; then mknod -m 644 /dev/random c 1 8; chown root:root /dev/random; fi
-  if [ ! -e /dev/urandom ]; then mknod -m 644 /dev/urandom c 1 9; chown root:root /dev/urandom; fi
-}
-
-create_privacyca_keys() {
-  # workaround for bug #568 - privacy ca takes 10-15 minutes to start first time, which is caused by key generation blocked due to not enough entropy in /dev/random
-  # for production, you just need to wait the 10-15 minutes because you want secure keys. but for automated testing we benefit by getting this done in 1 second instead of 900 seconds
-  if [[ "$PRIVACYCA_KEYGEN_URANDOM" == "yes" ]]; then
-    replace_random_until_exists "${intel_conf_dir}/PrivacyCA.p12" &
-  fi
-  # creates PrivacyCA.p12 and endorsement.p12  (also creates the cacerts and clientfiles dirs)
-  local oldpwd=`pwd`
-  cd "${intel_conf_dir}"
-  java -jar ${package_dir}/HisPrivacyCAWebServices2-setup.jar
-  cd "${oldpwd}"  
 }
 
 # The PrivacyCA creates PrivacyCA.p12 on start-up if it's missing; so we ensure it has safe permissions
 protect_privacyca_files() {
   local PRIVACYCA_FILES="${intel_conf_dir}/PrivacyCA.p12 ${intel_conf_dir}/PrivacyCA.properties ${intel_conf_dir}/clientfiles ${intel_conf_dir}/clientfiles.zip ${intel_conf_dir}/cacerts"
   chmod 600 $PRIVACYCA_FILES
-  glassfish_permissions $PRIVACYCA_FILES
+  if using_glassfish; then
+    glassfish_permissions $PRIVACYCA_FILES
+  elif using_tomcat; then
+    tomcat_permissions $PRIVACYCA_FILES
+  fi
 }
 
 RETVAL=0
@@ -145,20 +145,20 @@ case "$1" in
 	echo "Build ${BUILD:-Unknown}"
         ;;
   start)
-        webservice_start_report "${glassfish_application_name}"
+        webservice_start_report "${webservice_application_name}"
         protect_privacyca_files
         ;;
   stop)
-        webservice_stop_report "${glassfish_application_name}"
+        webservice_stop_report "${webservice_application_name}"
         ;;
   status)
         glassfish_running_report
-        webservice_running_report "${glassfish_application_name}"
+        webservice_running_report "${webservice_application_name}"
         ;;
   restart)
-        webservice_stop_report "${glassfish_application_name}"
+        webservice_stop_report "${webservice_application_name}"
         sleep 2
-        webservice_start_report "${glassfish_application_name}"
+        webservice_start_report "${webservice_application_name}"
         ;;
   glassfish-restart)
         glassfish_restart
@@ -186,7 +186,7 @@ case "$1" in
         ;;
   uninstall)
         datestr=`date +%Y-%m-%d.%H%M`
-        webservice_uninstall "${glassfish_application_name}"
+        webservice_uninstall "${webservice_application_name}"
         if [ -f "${package_config_filename}" ]; then
           mkdir -p "${intel_conf_dir}"
           cp "${package_config_filename}" "${intel_conf_dir}"/${package_name}.properties.${datestr}
@@ -203,7 +203,7 @@ case "$1" in
         ;;
   *)
         echo "Usage: ${script_name} {setup|start|stop|status|uninstall}"
-        exit 1
+        #exit 1
 esac
 
 exit $RETVAL
