new function in tagent to getNewid calling getNewid from setup_interactive_install instead of pcakey

diff --git a/installers/TrustAgentLinuxInstaller/src/files/tagent b/installers/TrustAgentLinuxInstaller/src/files/tagent
--- a/installers/TrustAgentLinuxInstaller/src/files/tagent
+++ b/installers/TrustAgentLinuxInstaller/src/files/tagent
@@ -180,6 +180,23 @@ function checkServiceStatus {
    fi
    return 0; }
    
+getNewid {
+  java_detect > /dev/null
+  if no_java $java_required_version; then echo "Cannot find Java $java_required_version or later"; exit 1; fi
+  stopService
+  if [ -f "$intel_conf_dir/cert/aikblob.dat" ]; then
+    backup_file "$intel_conf_dir/cert/aikblob.dat"
+    rm "$intel_conf_dir/cert/aikblob.dat"
+  fi
+  if [ -f "$intel_conf_dir/cert/aikcert.pem" ]; then
+    backup_file "$intel_conf_dir/cert/aikcert.pem"
+    rm "$intel_conf_dir/cert/aikcert.pem"
+  fi
+  pcakey
+  $java -cp $CLASSPATH $javaVMArgs -DforceCreateEk=true com.intel.mountwilson.trustagent.commands.CreateIdentityCmd
+  startService
+}
+
 setup_env() {
   yum_detect > /dev/null
   java_detect > /dev/null
@@ -219,7 +236,8 @@ setup_interactive_install() {
 	    stopService
         fi
         # This is the place to do any setup while trust agent is not running
-        /usr/local/bin/pcakey
+        #/usr/local/bin/pcakey
+        getNewid
 		if [ $? == 1 ]; then
 			exit 1
 		fi
@@ -269,6 +287,7 @@ function main {
         startService
         ;;
   newid)
+        #getNewid
         java_detect > /dev/null
         if no_java $java_required_version; then echo "Cannot find Java $java_required_version or later"; exit 1; fi
         stopService
