Fix for bug 516.  If wrong PrivacyCA user or password are provided then Tagent will exit out letting the user know to try again with correct user name or password

diff --git a/installers/TrustAgentLinuxInstaller/src/files/tagent b/installers/TrustAgentLinuxInstaller/src/files/tagent
--- a/installers/TrustAgentLinuxInstaller/src/files/tagent
+++ b/installers/TrustAgentLinuxInstaller/src/files/tagent
@@ -216,6 +216,10 @@ setup_interactive_install() {
         fi
         # This is the place to do any setup while trust agent is not running
         /usr/local/bin/pcakey
+		if [ $? == 1 ]; then
+			echo "Unable to download Privacy CA files: try 'pcakey' again, check server address, username, and password"
+			exit 1
+		fi
         # After setup is done, start the trust agent:
 	checkServiceStatus
 	if [ -z "$TRUST_AGENT_RUNNING" ]; then
