Revert "Merge remote-tracking branch 'remotes/origin/development' into issue-926-db-check"
This reverts commit 27c8d740df88b8ea033b08f45c84c3958df2148f, reversing
changes made to 35b313a8ec57ed2916b8f2ef22ba1ab212fa607c.

diff --git a/installers/AttestationServiceLinuxInstaller/src/files/asctl b/installers/AttestationServiceLinuxInstaller/src/files/asctl
--- a/installers/AttestationServiceLinuxInstaller/src/files/asctl
+++ b/installers/AttestationServiceLinuxInstaller/src/files/asctl
@@ -19,8 +19,7 @@ webservice_application_name=AttestationService
 #java_required_version=1.6.0_29
 
 # FUNCTION LIBRARY, VERSION INFORMATION, and LOCAL CONFIGURATION
-if [ -f /usr/share/mtwilson/script/functions ]; then . /usr/share/mtwilson/script/functions; else echo "Missing file: /usr/share/mtwilson/script/functions"; exit 1; fi
-#if [ -f "${package_dir}/functions" ]; then . "${package_dir}/functions"; else echo "Missing file: ${package_dir}/functions"; exit 1; fi
+if [ -f "${package_dir}/functions" ]; then . "${package_dir}/functions"; else echo "Missing file: ${package_dir}/functions"; exit 1; fi
 if [ -f "${package_dir}/version" ]; then . "${package_dir}/version"; else echo_warning "Missing file: ${package_dir}/version"; fi
 shell_include_files "${package_env_filename}" "${package_install_filename}"
 if [ -f /root/mtwilson.env ]; then  . /root/mtwilson.env; fi
@@ -88,8 +87,7 @@ download_privacyca_certs() {
     touch $zipfile
     chmod 600 $zipfile
     # XXX password in URL is insecure in systems that have user accounts or software which should not know this password
-	encodedPW=$(echo "${PRIVACYCA_DOWNLOAD_PASSWORD}" | sed -e 's/%/%25/g' -e 's/ /%20/g' -e 's/!/%21/g' -e 's/"/%22/g' -e 's/#/%23/g' -e 's/\$/%24/g' -e 's/\&/%26/g' -e 's/'\''/%27/g' -e 's/(/%28/g' -e 's/)/%29/g' -e 's/\*/%2a/g' -e 's/+/%2b/g' -e 's/,/%2c/g' -e 's/-/%2d/g' -e 's/\./%2e/g' -e 's/\//%2f/g' -e 's/:/%3a/g' -e 's/;/%3b/g' -e 's//%3e/g' -e 's/?/%3f/g' -e 's/@/%40/g' -e 's/\[/%5b/g' -e 's/\\/%5c/g' -e 's/\]/%5d/g' -e 's/\^/%5e/g' -e 's/_/%5f/g' -e 's/`/%60/g' -e 's/{/%7b/g' -e 's/|/%7c/g' -e 's/}/%7d/g' -e 's/~/%7e/g')
-    wget --no-proxy --no-check-certificate -q "https://${PRIVACYCA_SERVER}:$DEFAULT_API_PORT/HisPrivacyCAWebServices2/clientfiles.zip?user=${PRIVACYCA_DOWNLOAD_USERNAME}&password=${encodedPW}" -O ${zipfile}
+    wget --no-proxy --no-check-certificate -q "https://${PRIVACYCA_SERVER}:$DEFAULT_API_PORT/HisPrivacyCAWebServices2/clientfiles.zip?user=${PRIVACYCA_DOWNLOAD_USERNAME}&password=${PRIVACYCA_DOWNLOAD_PASSWORD}" -O ${zipfile}
     if [ -s ${zipfile} ]; then
       mkdir -p /tmp/clientfiles.x
       chmod -R 600 /tmp/clientfiles.x
