update mtwilson-linux-util usage in installers

diff --git a/installers/WLMServiceLinuxInstaller/src/files/wlmctl b/installers/WLMServiceLinuxInstaller/src/files/wlmctl
--- a/installers/WLMServiceLinuxInstaller/src/files/wlmctl
+++ b/installers/WLMServiceLinuxInstaller/src/files/wlmctl
@@ -26,7 +26,8 @@ webservice_application_name=WLMService
 
 
 # FUNCTION LIBRARY, VERSION INFORMATION, and LOCAL CONFIGURATION
-if [ -f "${package_dir}/functions" ]; then . "${package_dir}/functions"; else echo "Missing file: ${package_dir}/functions"; exit 1; fi
+if [ -f /usr/share/mtwilson/script/functions ]; then . /usr/share/mtwilson/script/functions; else echo "Missing file: /usr/share/mtwilson/script/functions"; exit 1; fi
+#if [ -f "${package_dir}/functions" ]; then . "${package_dir}/functions"; else echo "Missing file: ${package_dir}/functions"; exit 1; fi
 if [ -f "${package_dir}/version" ]; then . "${package_dir}/version"; else echo_warning "Missing file: ${package_dir}/version"; fi
 shell_include_files "${package_env_filename}" "${package_install_filename}"
 if [ -f /root/mtwilson.env ]; then  . /root/mtwilson.env; fi
