dev-2.0-sprint-1: updated java version in functions file

diff --git a/installers/LinuxUtil/src/files/functions b/installers/LinuxUtil/src/files/functions
--- a/installers/LinuxUtil/src/files/functions
+++ b/installers/LinuxUtil/src/files/functions
@@ -29,7 +29,7 @@ TERM_COLOR_NORMAL="\\033[0;39m"
 #DEFAULT_POSTGRES_PASSWORD=""
 #DEFAULT_POSTGRES_DATABASE="mw_as"
 
-DEFAULT_JAVA_REQUIRED_VERSION="1.6"
+DEFAULT_JAVA_REQUIRED_VERSION="1.7"
 DEFAULT_GLASSFISH_REQUIRED_VERSION="3.0"
 DEFAULT_TOMCAT_REQUIRED_VERSION="6.0"
 DEFAULT_MYSQL_REQUIRED_VERSION="5.0"
@@ -179,7 +179,7 @@ is_version_at_least() {
   fi  
 }
 
-# like is_version_at_least but works on entire java version string 1.6.0_29
+# like is_version_at_least but works on entire java version string 1.7.0_51
 # instead of just a major.minor number
 # Parameters:
 # - version to test (of installed software)
@@ -2087,7 +2087,7 @@ glassfish_create_ssl_cert_prompt() {
     prompt_yes_no GLASSFISH_CREATE_SSL_CERT "Do you want to set up an SSL certificate for Glassfish?"
     echo
     if [ "${GLASSFISH_CREATE_SSL_CERT}" == "yes" ]; then
-      if no_java ${JAVA_REQUIRED_VERSION:-1.6}; then echo "Cannot find Java ${JAVA_REQUIRED_VERSION:-1.6} or later"; return 1; fi
+      if no_java ${JAVA_REQUIRED_VERSION:-1.7}; then echo "Cannot find Java ${JAVA_REQUIRED_VERSION:-1.7} or later"; return 1; fi
       glassfish_require
       prompt_with_default GLASSFISH_SSL_CERT_CN "Domain name for SSL Certificate:" ${MTWILSON_SERVER:-127.0.0.1}
       glassfish_create_ssl_cert "${GLASSFISH_SSL_CERT_CN}"
@@ -2116,7 +2116,7 @@ function valid_ip() {
 glassfish_create_ssl_cert() {
 #  echo_warning "This feature has been disabled: glassfish_create_ssl_cert"
 #  return
-  if no_java ${JAVA_REQUIRED_VERSION:-1.6}; then echo "Cannot find Java ${JAVA_REQUIRED_VERSION:-1.6} or later"; return 1; fi
+  if no_java ${JAVA_REQUIRED_VERSION:-1.7}; then echo "Cannot find Java ${JAVA_REQUIRED_VERSION:-1.7} or later"; return 1; fi
   glassfish_require
   local serverName="${1}"
   local keystorePassword=changeit
@@ -2219,7 +2219,7 @@ tomcat_version() {
 #Using CATALINA_BASE:   /usr/share/apache-tomcat-6.0.29
 #Using CATALINA_HOME:   /usr/share/apache-tomcat-6.0.29
 #Using CATALINA_TMPDIR: /usr/share/apache-tomcat-6.0.29/temp
-#Using JRE_HOME:        /usr/share/jdk1.6.0_29
+#Using JRE_HOME:        /usr/share/jdk1.7.0_51
 #Using CLASSPATH:       /usr/share/apache-tomcat-6.0.29/bin/bootstrap.jar
 #Server version: Apache Tomcat/6.0.29
 #Server built:   July 19 2010 1458
@@ -2227,7 +2227,7 @@ tomcat_version() {
 #OS Name:        Linux
 #OS Version:     3.0.0-12-server
 #Architecture:   amd64
-#JVM Version:    1.6.0_29-b11
+#JVM Version:    1.7.0_51
 #JVM Vendor:     Sun Microsystems Inc.
 
 
@@ -2426,7 +2426,7 @@ tomcat_create_ssl_cert_prompt() {
     prompt_yes_no TOMCAT_CREATE_SSL_CERT "Do you want to set up an SSL certificate for Tomcat?"
     echo
     if [ "${TOMCAT_CREATE_SSL_CERT}" == "yes" ]; then
-      if no_java ${JAVA_REQUIRED_VERSION:-1.6}; then echo "Cannot find Java ${JAVA_REQUIRED_VERSION:-1.6} or later"; return 1; fi
+      if no_java ${JAVA_REQUIRED_VERSION:-1.7}; then echo "Cannot find Java ${JAVA_REQUIRED_VERSION:-1.7} or later"; return 1; fi
       tomcat_require
       prompt_with_default TOMCAT_SSL_CERT_CN "Domain name for SSL Certificate:" ${MTWILSON_SERVER:-127.0.0.1}
       tomcat_create_ssl_cert "${TOMCAT_SSL_CERT_CN}"
@@ -2439,7 +2439,7 @@ tomcat_create_ssl_cert_prompt() {
 tomcat_create_ssl_cert() {
 #  echo_warning "This feature has been disabled: tomcat_create_ssl_cert"
 #  return
-  if no_java ${JAVA_REQUIRED_VERSION:-1.6}; then echo "Cannot find Java ${JAVA_REQUIRED_VERSION:-1.6} or later"; return 1; fi
+  if no_java ${JAVA_REQUIRED_VERSION:-1.7}; then echo "Cannot find Java ${JAVA_REQUIRED_VERSION:-1.7} or later"; return 1; fi
   tomcat_require
   
 
@@ -2586,7 +2586,7 @@ java_ready() {
 #    (or if you are calling this from java_detect you set it yourself)
 java_version() {
   if [ -n "$java" ]; then
-    # extract the version number from a string like: java version "1.6.0_29"
+    # extract the version number from a string like: java version "1.7.0_51"
     local current_java_version=`$java -version 2>&1 | head -n 1 | sed -e 's/"//g' | awk '{ print $3 }'`
     if [ -n "$current_java_version" ]; then
       echo $current_java_version
@@ -2620,7 +2620,7 @@ java_version_report() {
 # but because if the system administrator has bothered to install the JDK or JRE
 # it's clear he prefers to use that over the system-provided java.
 # Environment:
-# - JAVA_REQUIRED_VERSION should be set like 1.6 or 1.6.0_29 ; if not set then DEFAULT_JAVA_REQUIRED_VERSION is used
+# - JAVA_REQUIRED_VERSION should be set like 1.7 or 1.7.0_51 ; if not set then DEFAULT_JAVA_REQUIRED_VERSION is used
 # Return code:  0 if java matching minimum version is found, 1 otherwise
 # Postcondition:  on success, JAVA_HOME, java, and JAVA_VERSION are set;  on failure to find java they are cleared
 java_detect() {
@@ -2719,7 +2719,7 @@ java_env_report() {
 # if they are not configured it initiates java detect to find them
 # if
 # Environment:
-# - JAVA_REQUIRED_VERSION in the format "1.6.0_29" (or pass it as a parameter)
+# - JAVA_REQUIRED_VERSION in the format "1.7.0_51" (or pass it as a parameter)
 java_require() {
   local min_version="${1:-${JAVA_REQUIRED_VERSION:-${DEFAULT_JAVA_REQUIRED_VERSION}}}"
   if [[ -z "$JAVA_HOME" || -z "$java" || ! -f "$java" ]]; then
@@ -2733,17 +2733,17 @@ java_require() {
   return 1
 }
 
-# usage:  if no_java 1.6; then echo_failure "Cannot find Java"; exit 1; fi
+# usage:  if no_java 1.7; then echo_failure "Cannot find Java"; exit 1; fi
 no_java() {
   java_require $1
   if [ $? -eq 0 ]; then return 1; else return 0; fi
 }
 
 # Environment:
-# - JAVA_REQUIRED_VERSION in the format "1.6.0_29"
+# - JAVA_REQUIRED_VERSION in the format "1.7.0_51"
 java_install_openjdk() {
-  JAVA_YUM_PACKAGES="java-1.6.0-openjdk java-1.6.0-openjdk-devel"
-  JAVA_APT_PACKAGES="openjdk-6-jre openjdk-6-jdk"
+  JAVA_YUM_PACKAGES="java-1.7.0-openjdk java-1.7.0-openjdk-devel"
+  JAVA_APT_PACKAGES="openjdk-7-jre openjdk-7-jdk"
   java_detect
   if [[ -z "$JAVA_HOME" || -z "$java" ]]; then
     auto_install "Java" "JAVA"
@@ -2759,12 +2759,12 @@ java_install_openjdk() {
 }
 
 java_install() {
-  local JAVA_PACKAGE="${1-:jdk-6u29-linux-x64.bin}"
-#  JAVA_YUM_PACKAGES="java-1.6.0-openjdk java-1.6.0-openjdk-devel"
-#  JAVA_APT_PACKAGES="openjdk-6-jre openjdk-6-jdk"
+  local JAVA_PACKAGE="${1-:jdk-7u51-linux-x64.bin}"
+#  JAVA_YUM_PACKAGES="java-1.7.0-openjdk java-1.7.0-openjdk-devel"
+#  JAVA_APT_PACKAGES="openjdk-7-jre openjdk-7-jdk"
 #  auto_install "Java" "JAVA"
   java_clear; java_detect >> $INSTALL_LOG_FILE
-  if no_java ${JAVA_REQUIRED_VERSION:-1.6} >> $INSTALL_LOG_FILE; then
+  if no_java ${JAVA_REQUIRED_VERSION:-1.7} >> $INSTALL_LOG_FILE; then
     if [[ -z "$JAVA_PACKAGE" || ! -f "$JAVA_PACKAGE" ]]; then
       echo_failure "Missing Java installer: $JAVA_PACKAGE" | tee -a 
       return 1
@@ -3193,7 +3193,7 @@ set_config_db_properties() {
 # The EclipseLink persistence framework sends messages to stdout that start with the text [EL Info] or [EL Warning].
 # We suppress those because they are not useful for the customer, only for debugging.
 call_setupcommand() {
-  if no_java ${java_required_version:-1.6}; then echo "Cannot find Java ${java_required_version:-1.6} or later"; return 1; fi
+  if no_java ${java_required_version:-1.7}; then echo "Cannot find Java ${java_required_version:-1.7} or later"; return 1; fi
   SETUP_CONSOLE_JARS=$(JARS=(${setupconsole_dir}/*.jar); IFS=:; echo "${JARS[*]}")
   mainclass=com.intel.mtwilson.setup.TextConsole
   $java -cp "$SETUP_CONSOLE_JARS" -Dlogback.configurationFile=${conf_dir}/logback-stderr.xml $mainclass $@ | grep -vE "^\[EL Info\]|^\[EL Warning\]" 2> /var/log/mtwilson.log
