fixing java detection behavior in installers and control scripts

diff --git a/installers/LinuxUtil/src/files/functions b/installers/LinuxUtil/src/files/functions
--- a/installers/LinuxUtil/src/files/functions
+++ b/installers/LinuxUtil/src/files/functions
@@ -19,6 +19,7 @@ DEFAULT_MYSQL_PORTNUM="3306"
 DEFAULT_MYSQL_USERNAME="root"
 DEFAULT_MYSQL_PASSWORD=""
 DEFAULT_MYSQL_DATABASE="mw_as"
+DEFAULT_JAVA_REQUIRED_VERSION="1.6"
 
 export INSTALL_LOG_FILE=/tmp/mtwilson-install.log
 
@@ -1448,7 +1449,7 @@ glassfish_create_ssl_cert_prompt() {
     prompt_yes_no GLASSFISH_CREATE_SSL_CERT "Do you want to set up an SSL certificate for Glassfish?"
     echo
     if [ "${GLASSFISH_CREATE_SSL_CERT}" == "yes" ]; then
-      java_require
+      if no_java ${java_required_version:-1.6}; then echo "Cannot find Java ${java_required_version:-1.6} or later"; return 1; fi
       glassfish_require
       local ssl_domain
       echo -n "Domain name for SSL Certificate [127.0.0.1]: "
@@ -1465,7 +1466,7 @@ glassfish_create_ssl_cert_prompt() {
 glassfish_create_ssl_cert() {
   echo_warning "This feature has been disabled: glassfish_create_ssl_cert"
   return
-  java_require
+  if no_java ${java_required_version:-1.6}; then echo "Cannot find Java ${java_required_version:-1.6} or later"; return 1; fi
   glassfish_require
   local serverName="${1}"
   local keystorePassword=changeit
@@ -1601,30 +1602,42 @@ tomcat_install() {
 java_clear() {
   JAVA_HOME=""
   java=""
+  JAVA_VERSION=""
 }
 
 
-# checks if the version of the currently configured java meets the minimum
-# requirement. if not, then it resets the java variables.
+# prints the current java version
+# return codes:
+# 0 - success
+# 1 - java command not found
+# 2 - cannot get version number using java command
 # Environment:
-# - java_required_version (or pass it as a parameter)
+# - java  (path to java binary) you can get it by calling java_detect 
+#    (or if you are calling this from java_detect you set it yourself)
 java_version() {
   if [ -n "$java" ]; then
     # extract the version number from a string like: java version "1.6.0_29"
-    JAVA_VERSION=`$java -version 2>&1 | head -n 1 | sed -e 's/"//g' | awk '{ print $3 }'`
+    local current_java_version=`$java -version 2>&1 | head -n 1 | sed -e 's/"//g' | awk '{ print $3 }'`
+    if [ -n "$current_java_version" ]; then
+      echo $current_java_version
+      return 0
+    fi
+    return 2
   fi
+  return 1
 }
 
 # Environment:
 # - java_required_version
 java_version_report() {
-  local min_version="${1:-${java_required_version}}"
-  java_version
-  if is_java_version_at_least "$JAVA_VERSION" "${min_version}"; then
-    echo_success "Java version $JAVA_VERSION is ok"
+  local min_version="${1:-${JAVA_REQUIRED_VERSION:-${DEFAULT_JAVA_REQUIRED_VERSION}}"
+  local current_version=`java_version`
+  if is_java_version_at_least "$current_version" "${min_version}"; then
+    echo_success "Java version $current_version is ok"
+    return 0
   else
-    echo_warning "Java version $JAVA_VERSION is not supported, minimum is ${java_required_version}"
-    java_clear
+    echo_warning "Java version $current_version is not supported, minimum is ${min_version}"
+    return 1
   fi
 }
 
@@ -1637,68 +1650,89 @@ java_version_report() {
 # but because if the system administrator has bothered to install the JDK or JRE
 # it's clear he prefers to use that over the system-provided java.
 # Environment:
-# - java_required_version
+# - JAVA_REQUIRED_VERSION should be set like 1.6 or 1.6.0_29 ; if not set then DEFAULT_JAVA_REQUIRED_VERSION is used
+# Return code:  0 if java matching minimum version is found, 1 otherwise
+# Postcondition:  on success, JAVA_HOME, java, and JAVA_VERSION are set;  on failure to find java they are cleared
 java_detect() {
-  local min_version="${1:-${java_required_version}}"
-  if [[ -z "$JAVA_HOME" || -z "$java" ]]; then
+  local min_version="${1:-${JAVA_REQUIRED_VERSION:-${DEFAULT_JAVA_REQUIRED_VERSION}}}"
+  # start with JAVA_HOME if it is already configured
+  if [[ -n "$JAVA_HOME" ]]; then
+    java=${JAVA_HOME}/bin/java
+    JAVA_VERSION=`java_version`
+    if is_java_version_at_least "$JAVA_VERSION" "${min_version}"; then
+      return 0
+    fi
+  fi
+
     JAVA_JDK_CANDIDATES=`find / -name java 2>/dev/null | grep jdk | grep -v jre | grep bin/java`
     for c in $JAVA_JDK_CANDIDATES
     do
-      if [[ -z "$JAVA_HOME" ]]; then
-        java_bindir=`dirname $c`
+        local java_bindir=`dirname $c`
         if [ -f "$java_bindir/java" ]; then
           JAVA_HOME=`dirname $java_bindir`
           java=$c
+          JAVA_VERSION=`java_version`
           echo "Found Java: $JAVA_HOME"
-          java_version ${min_version}
+          if is_java_version_at_least "$JAVA_VERSION" "${min_version}"; then
+            return 0
+          fi
         fi
-      fi
     done
-  fi
-  if [[ -z "$JAVA_HOME" || -z "$java" ]]; then
+    
     echo "Cannot find JDK"
+
     JAVA_JRE_CANDIDATES=`find / -name java 2>/dev/null | grep jre | grep bin/java`
     for c in $JAVA_JRE_CANDIDATES
     do
-      if [[ -z "$JAVA_HOME" ]]; then
         java_bindir=`dirname $c`
         if [ -f "$java_bindir/java" ]; then
           JAVA_HOME=`dirname $java_bindir`
           java=$c
+          JAVA_VERSION=`java_version`
           echo "Found Java: $JAVA_HOME"
-          java_version ${min_version}
+          if is_java_version_at_least "$JAVA_VERSION" "${min_version}"; then
+            return 0
+          fi
         fi
-      fi
     done
-  fi
-  if [[ -z "$JAVA_HOME" || -z "$java" ]]; then
+
     echo "Cannot find JRE"
+
     JAVA_BIN_CANDIDATES=`find / -name java 2>/dev/null | grep bin/java`
     for c in $JAVA_BIN_CANDIDATES
     do
-      if [[ -z "$JAVA_HOME" ]]; then
         java_bindir=`dirname $c`
         # in non-JDK and non-JRE folders the "java" command may be a symlink:
         if [ -f "$java_bindir/java" ]; then
           JAVA_HOME=`dirname $java_bindir`
           java=$c
+          JAVA_VERSION=`java_version`
           echo "Found Java: $c"
-          java_version ${min_version}
+          if is_java_version_at_least "$JAVA_VERSION" "${min_version}"; then
+            return 0
+          fi
         elif [ -h "$java_bindir/java" ]; then
           local javatarget=`readlink $c`
           if [ -f "$javatarget" ]; then
             java_bindir=`dirname $javatarget`
             JAVA_HOME=`dirname $java_bindir`
             java=$javatarget
+            JAVA_VERSION=`java_version`
             echo "Found Java: $java"
-            java_version ${min_version}
+            if is_java_version_at_least "$JAVA_VERSION" "${min_version}"; then
+              return 0
+            fi
           else
-            echo "Broken link $c -> $javatarget"
+            echo_warning "Broken link $c -> $javatarget"
           fi
         fi
-      fi
     done
-  fi
+
+    echo "Cannot find system Java"
+
+  echo_failure "Cannot find Java"
+  java_clear
+  return 1
 }
 
 # must load from config file or call java_detect prior to calling this function
@@ -1708,17 +1742,29 @@ java_env_report() {
   echo "java=$java"
 }
 
+
+# if java home and java bin are already configured and meet the minimum version, does nothing
+# if they are not configured it initiates java detect to find them
+# if
 # Environment:
 # - java_required_version in the format "1.6.0_29" (or pass it as a parameter)
 java_require() {
-  local min_version="${1:-${java_required_version}}"
+  local min_version="${1:-${JAVA_REQUIRED_VERSION:-${DEFAULT_JAVA_REQUIRED_VERSION}}}"
   if [[ -z "$JAVA_HOME" || -z "$java" || ! -f "$java" ]]; then
     java_detect ${min_version} > /dev/null
   fi
-  if [[ -z "$JAVA_HOME" || -z "$java" || ! -f "$java" ]]; then
-    echo_failure "Cannot find Java version $java_required_version or later"
-    exit 1
+  JAVA_VERSION=`java_version`
+  if is_java_version_at_least "$JAVA_VERSION" "${min_version}"; then
+    return 0
   fi
+  echo_failure "Cannot find Java version $min_version or later"
+  return 1
+}
+
+# usage:  if no_java 1.6; then echo_failure "Cannot find Java"; exit 1; fi
+no_java() {
+  java_require $1
+  if [ $? -eq 0 ]; then return 1; else return 0; fi
 }
 
 # Environment:
diff --git a/installers/LinuxUtil/src/files/mtwilson b/installers/LinuxUtil/src/files/mtwilson
--- a/installers/LinuxUtil/src/files/mtwilson
+++ b/installers/LinuxUtil/src/files/mtwilson
@@ -13,7 +13,7 @@ conf_dir=/etc/intel/cloudsecurity
 #apiclient_shell=${apiclient_dir}/shell
 mysql_required_version=5.0
 glassfish_required_version=3.0
-java_required_version=1.6.0_29
+#java_required_version=1.6.0_29
 
 # FUNCTION LIBRARY and VERSION INFORMATION
 if [ -f ${share_dir}/functions ]; then  . ${share_dir}/functions; else echo "Missing file: ${share_dir}/functions";   exit 1; fi
@@ -36,17 +36,18 @@ if using_glassfish; then
 elif using_tomcat; then
     export tomcat_required_version=${TOMCAT_REQUIRED_VERSION:-8.4}
 fi
-export java_required_version=${JAVA_REQUIRED_VERSION:-1.6.0_29}
+export JAVA_REQUIRED_VERSION=${JAVA_REQUIRED_VERSION:-1.6.0_29}
+export java_required_version=${JAVA_REQUIRED_VERSION}
 
 call_apiclient() {
-  java_require
+  if no_java ${java_required_version:-1.6}; then echo "Cannot find Java ${java_required_version:-1.6} or later"; return 1; fi
   APICLIENT_JARS=$(JARS=(${apiclient_java}/*.jar); IFS=:; echo "${JARS[*]}")
   mainclass=com.intel.mtwilson.client.TextConsole
   $java -cp "$APICLIENT_JARS" $mainclass $@
 }
 
 call_setupcommand() {
-  java_require
+  if no_java ${java_required_version:-1.6}; then echo "Cannot find Java ${java_required_version:-1.6} or later"; return 1; fi
   SETUP_CONSOLE_JARS=$(JARS=(${setupconsole_dir}/*.jar); IFS=:; echo "${JARS[*]}")
   mainclass=com.intel.mtwilson.setup.TextConsole
   $java -cp "$SETUP_CONSOLE_JARS" $mainclass $@
@@ -196,24 +197,28 @@ case "$1" in
         setup_env
         ;;
   glassfish-detect)
-        java_require
+        if no_java ${java_required_version:-1.6}; then echo "Cannot find Java ${java_required_version:-1.6} or later"; exit 1; fi
         glassfish_detect ${2:-$glassfish_required_version}
         glassfish_env_report
         ;;
   glassfish-start)
-        java_require; glassfish_require
+        if no_java ${java_required_version:-1.6}; then echo "Cannot find Java ${java_required_version:-1.6} or later"; exit 1; fi
+        glassfish_require
         glassfish_start_report
         ;;
   glassfish-stop)
-        java_require; glassfish_require
+        if no_java ${java_required_version:-1.6}; then echo "Cannot find Java ${java_required_version:-1.6} or later"; exit 1; fi
+        glassfish_require
         glassfish_shutdown
         ;;
   glassfish-restart)
-        java_require; glassfish_require
+        if no_java ${java_required_version:-1.6}; then echo "Cannot find Java ${java_required_version:-1.6} or later"; exit 1; fi
+        glassfish_require
         glassfish_restart
         ;;
   glassfish-status)
-        java_require; glassfish_require
+        if no_java ${java_required_version:-1.6}; then echo "Cannot find Java ${java_required_version:-1.6} or later"; exit 1; fi
+        glassfish_require
         glassfish_running_report
         glassfish_sslcert_report
         ;;
@@ -237,7 +242,7 @@ case "$1" in
         mysql_create_ssl "Trust Dashboard"
         ;;
   java-detect)
-        java_detect ${2:-$java_required_version}
+        java_detect ${2:-${java_required_version:-${JAVA_REQUIRED_VERSION:-1.6}}
         java_env_report
         ;;
   api)
@@ -256,7 +261,8 @@ case "$1" in
         # show server ssh fingerprint, glassfish ssl fingerprint, and saml cert fingerprint
         echo "== SSH HOST KEYS =="
         ssh_fingerprints
-        java_require; glassfish_require
+        if no_java ${java_required_version:-1.6}; then echo "Cannot find Java ${java_required_version:-1.6} or later"; exit 1; fi
+        glassfish_require
         echo "== GLASSFISH SSL CERTIFICATE =="
         glassfish_sslcert_report
         echo "== MT WILSON SAML CERTIFICATE =="
@@ -269,7 +275,8 @@ case "$1" in
         erase_data_with_user_confirmation
         ;;
   uninstall)
-        java_require; glassfish_require
+        if no_java ${java_required_version:-1.6}; then echo "Cannot find Java ${java_required_version:-1.6} or later"; exit 1; fi
+        glassfish_require
         echo "Stopping Glassfish..."
         glassfish_shutdown
         # application files
diff --git a/installers/ManagementServiceLinuxInstaller/src/files/msctl b/installers/ManagementServiceLinuxInstaller/src/files/msctl
--- a/installers/ManagementServiceLinuxInstaller/src/files/msctl
+++ b/installers/ManagementServiceLinuxInstaller/src/files/msctl
@@ -17,7 +17,7 @@ mysql_setup_log=/var/log/intel.${package_name}.install.log
 mysql_script_dir=${package_dir}/database
 glassfish_required_version=3.0
 glassfish_application_name=ManagementService
-java_required_version=1.6.0_29
+#java_required_version=1.6.0_29
 
 # FUNCTION LIBRARY, VERSION INFORMATION, and LOCAL CONFIGURATION
 if [ -f "${package_dir}/functions" ]; then . "${package_dir}/functions"; else echo "Missing file: ${package_dir}/functions"; exit 1; fi
@@ -90,7 +90,7 @@ bootstrap_ms_internal_user() {
 # - Key alias (such as "admin", corresponding to "admin.jks" in the user directory)
 # - Key password
 bootstrap_ms_approve_user() {
-  java_require
+  if no_java ${java_required_version:-1.6}; then echo "Cannot find Java ${java_required_version:-1.6} or later"; exit 1; fi
   keytool=${JAVA_HOME}/bin/keytool
   local key_dir="${1}"
   local key_alias="${2}"
diff --git a/installers/TrustAgentLinuxInstaller/src/files/tagent b/installers/TrustAgentLinuxInstaller/src/files/tagent
--- a/installers/TrustAgentLinuxInstaller/src/files/tagent
+++ b/installers/TrustAgentLinuxInstaller/src/files/tagent
@@ -132,7 +132,7 @@ function startService {
         setup_env > "${package_env_filename}"
         read_local_config
     fi
-    java_require
+    if no_java $java_required_version; then echo "Cannot find Java $java_required_version or later"; exit 1; fi
 
    # make sure we have files from privacy ca
    report_files_exist /etc/intel/cloudsecurity/PrivacyCA.cer /etc/intel/cloudsecurity/hisprovisioner.properties
@@ -175,7 +175,7 @@ function checkServiceStatus {
    
 setup_env() {
   yum_detect > /dev/null
-  java_clear; java_detect > /dev/null
+  java_detect > /dev/null
   local datestr=`date +%Y-%m-%d.%H%M`
   echo "# environment on ${datestr}"
   echo "JAVA_HOME=$JAVA_HOME"
@@ -183,11 +183,11 @@ setup_env() {
 }
 
 setup() {
-  yum_detect
-  java_clear; java_detect
+  yum_detect > /dev/null
+  java_detect > /dev/null
   read_local_config
   if [[ -z "$JAVA_HOME" ]]; then
-      echo "Missing one or more required packages"
+      echo_failure "Cannot find Java"
       setup_print_summary
       exit 1
   fi
