dev-2.0-sprint-1: updated all java_required_version and JAVA_REQUIRED_VERSION variables, even comments

diff --git a/installers/LinuxUtil/src/files/mtwilson b/installers/LinuxUtil/src/files/mtwilson
--- a/installers/LinuxUtil/src/files/mtwilson
+++ b/installers/LinuxUtil/src/files/mtwilson
@@ -13,7 +13,7 @@ conf_dir=/etc/intel/cloudsecurity
 #apiclient_shell=${apiclient_dir}/shell
 #mysql_required_version=5.0
 #glassfish_required_version=3.0
-#java_required_version=1.6.0_29
+#java_required_version=1.7.0_51
 
 # FUNCTION LIBRARY and VERSION INFORMATION
 if [ -f ${share_dir}/functions ]; then  . ${share_dir}/functions; else echo "Missing file: ${share_dir}/functions";   exit 1; fi
@@ -50,7 +50,7 @@ export JAVA_REQUIRED_VERSION=${JAVA_REQUIRED_VERSION:-1.7.0_51} #1.6.0_29}
 export java_required_version=${JAVA_REQUIRED_VERSION}
 
 call_apiclient() {
-  if no_java ${java_required_version:-1.6}; then echo "Cannot find Java ${java_required_version:-1.6} or later"; return 1; fi
+  if no_java ${java_required_version:-1.7}; then echo "Cannot find Java ${java_required_version:-1.7} or later"; return 1; fi
   APICLIENT_JARS=$(JARS=(${apiclient_java}/*.jar); IFS=:; echo "${JARS[*]}")
   mainclass=com.intel.mtwilson.client.TextConsole
   $java -cp "$APICLIENT_JARS" -Dlogback.configurationFile=${conf_dir}/logback.xml $mainclass $@
@@ -214,7 +214,7 @@ case "$1" in
         setup_env
         ;;
   start)
-        if no_java ${java_required_version:-1.6}; then echo "Cannot find Java ${java_required_version:-1.6} or later"; exit 1; fi
+        if no_java ${java_required_version:-1.7}; then echo "Cannot find Java ${java_required_version:-1.7} or later"; exit 1; fi
         if using_glassfish; then
 		  glassfish_require
           glassfish_start_report
@@ -224,7 +224,7 @@ case "$1" in
         fi
         ;;
   stop)
-        if no_java ${java_required_version:-1.6}; then echo "Cannot find Java ${java_required_version:-1.6} or later"; exit 1; fi
+        if no_java ${java_required_version:-1.7}; then echo "Cannot find Java ${java_required_version:-1.7} or later"; exit 1; fi
         if using_glassfish; then
 		  glassfish_require
           glassfish_shutdown
@@ -234,7 +234,7 @@ case "$1" in
         fi
         ;;
   restart)
-        if no_java ${java_required_version:-1.6}; then echo "Cannot find Java ${java_required_version:-1.6} or later"; exit 1; fi
+        if no_java ${java_required_version:-1.7}; then echo "Cannot find Java ${java_required_version:-1.7} or later"; exit 1; fi
         if using_glassfish; then
 		  glassfish_require
           glassfish_restart
@@ -244,27 +244,27 @@ case "$1" in
         fi
         ;;
   glassfish-detect)
-        if no_java ${java_required_version:-1.6}; then echo "Cannot find Java ${java_required_version:-1.6} or later"; exit 1; fi
+        if no_java ${java_required_version:-1.7}; then echo "Cannot find Java ${java_required_version:-1.7} or later"; exit 1; fi
         glassfish_detect ${2:-$GLASSFISH_REQUIRED_VERSION}
         glassfish_env_report
         ;;
   glassfish-start)
-        if no_java ${java_required_version:-1.6}; then echo "Cannot find Java ${java_required_version:-1.6} or later"; exit 1; fi
+        if no_java ${java_required_version:-1.7}; then echo "Cannot find Java ${java_required_version:-1.7} or later"; exit 1; fi
         glassfish_require
         glassfish_start_report
         ;;
   glassfish-stop)
-        if no_java ${java_required_version:-1.6}; then echo "Cannot find Java ${java_required_version:-1.6} or later"; exit 1; fi
+        if no_java ${java_required_version:-1.7}; then echo "Cannot find Java ${java_required_version:-1.7} or later"; exit 1; fi
         glassfish_require
         glassfish_shutdown
         ;;
   glassfish-restart)
-        if no_java ${java_required_version:-1.6}; then echo "Cannot find Java ${java_required_version:-1.6} or later"; exit 1; fi
+        if no_java ${java_required_version:-1.7}; then echo "Cannot find Java ${java_required_version:-1.7} or later"; exit 1; fi
         glassfish_require
         glassfish_restart
         ;;
   glassfish-status)
-        if no_java ${java_required_version:-1.6}; then echo "Cannot find Java ${java_required_version:-1.6} or later"; exit 1; fi
+        if no_java ${java_required_version:-1.7}; then echo "Cannot find Java ${java_required_version:-1.7} or later"; exit 1; fi
         glassfish_require
         glassfish_running_report
         glassfish_sslcert_report
@@ -277,27 +277,27 @@ case "$1" in
         glassfish_enable_logging
         ;;
   tomcat-detect)
-        if no_java ${java_required_version:-1.6}; then echo "Cannot find Java ${java_required_version:-1.6} or later"; exit 1; fi
+        if no_java ${java_required_version:-1.7}; then echo "Cannot find Java ${java_required_version:-1.7} or later"; exit 1; fi
         tomcat_detect ${2:-$TOMCAT_REQUIRED_VERSION}
         tomcat_env_report
         ;;
   tomcat-start)
-        if no_java ${java_required_version:-1.6}; then echo "Cannot find Java ${java_required_version:-1.6} or later"; exit 1; fi
+        if no_java ${java_required_version:-1.7}; then echo "Cannot find Java ${java_required_version:-1.7} or later"; exit 1; fi
         tomcat_require
         tomcat_start_report
         ;;
   tomcat-stop)
-        if no_java ${java_required_version:-1.6}; then echo "Cannot find Java ${java_required_version:-1.6} or later"; exit 1; fi
+        if no_java ${java_required_version:-1.7}; then echo "Cannot find Java ${java_required_version:-1.7} or later"; exit 1; fi
         tomcat_require
         tomcat_shutdown
         ;;
   tomcat-restart)
-        if no_java ${java_required_version:-1.6}; then echo "Cannot find Java ${java_required_version:-1.6} or later"; exit 1; fi
+        if no_java ${java_required_version:-1.7}; then echo "Cannot find Java ${java_required_version:-1.7} or later"; exit 1; fi
         tomcat_require
         tomcat_restart
         ;;
   tomcat-status)
-        if no_java ${java_required_version:-1.6}; then echo "Cannot find Java ${java_required_version:-1.6} or later"; exit 1; fi
+        if no_java ${java_required_version:-1.7}; then echo "Cannot find Java ${java_required_version:-1.7} or later"; exit 1; fi
         tomcat_require
         tomcat_running_report
         tomcat_sslcert_report
@@ -341,7 +341,7 @@ case "$1" in
         # show server ssh fingerprint, glassfish ssl fingerprint, and saml cert fingerprint
         echo "== SSH HOST KEYS =="
         ssh_fingerprints
-        if no_java ${java_required_version:-1.6}; then echo "Cannot find Java ${java_required_version:-1.6} or later"; exit 1; fi
+        if no_java ${java_required_version:-1.7}; then echo "Cannot find Java ${java_required_version:-1.7} or later"; exit 1; fi
         if using_glassfish; then
           glassfish_require
           echo "== GLASSFISH SSL CERTIFICATE =="
@@ -377,7 +377,7 @@ case "$1" in
         change_db_pass
         ;;
   uninstall)
-        if no_java ${java_required_version:-1.6}; then echo "Cannot find Java ${java_required_version:-1.6} or later"; exit 1; fi
+        if no_java ${java_required_version:-1.7}; then echo "Cannot find Java ${java_required_version:-1.7} or later"; exit 1; fi
         #load_default_env 1>/dev/null
         if using_glassfish; then
           glassfish_require
diff --git a/installers/ManagementServiceLinuxInstaller/src/files/msctl b/installers/ManagementServiceLinuxInstaller/src/files/msctl
--- a/installers/ManagementServiceLinuxInstaller/src/files/msctl
+++ b/installers/ManagementServiceLinuxInstaller/src/files/msctl
@@ -17,7 +17,7 @@ package_keystore_users_dir=/var/opt/intel/${package_name}/users
 #mysql_script_dir=${package_dir}/database
 #glassfish_required_version=3.0
 webservice_application_name=ManagementService
-#java_required_version=1.6.0_29
+#java_required_version=1.7.0_51
 
 # FUNCTION LIBRARY, VERSION INFORMATION, and LOCAL CONFIGURATION
 if [ -f "${package_dir}/functions" ]; then . "${package_dir}/functions"; else echo "Missing file: ${package_dir}/functions"; exit 1; fi
@@ -94,7 +94,7 @@ bootstrap_ms_internal_user() {
 # - Key alias (such as "admin", corresponding to "admin.jks" in the user directory)
 # - Key password
 bootstrap_ms_approve_user() {
-  if no_java ${java_required_version:-1.6}; then echo "Cannot find Java ${java_required_version:-1.6} or later"; exit 1; fi
+  if no_java ${java_required_version:-1.7}; then echo "Cannot find Java ${java_required_version:-1.7} or later"; exit 1; fi
   keytool=${JAVA_HOME}/bin/keytool
   local key_dir="${1}"
   local key_alias="${2}"
